server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: EchoPay
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DBUSERNAME:postgres}
    password: ${DBPASSWORD:postgres}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dev}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-processor-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: echopay